/**
 * Babel config file.
 *
 * @since 1.0.0
 *
 * @internal Babel is aware of this config file's location.
 *
 * @internal PLEASE DO NOT EDIT THIS FILE!
 * This file and the contents of it are updated automatically.
 * Instead of editing, please see source repository @ <https://git.io/JD8Zo>.
 */

module.exports = function ( api ) {
	api.cache( false );

	return {
		presets : [ '@babel/preset-env', '@babel/preset-react', '@linaria' ],
	};
};
